### ISSUE TITLE
SourceControl: Error: Operation 'UpdateChangelistsStatus' not supported by source control provider 'Git LFS 2'

### ISSUE THREAD

**Issue by Karbonforms** [SRombauts/UEGitPlugin#177]
`SourceControl: Error: Operation 'UpdateChangelistsStatus' not supported by source control provider 'Git LFS 2'`

What's going on here?

**Comment by SRombauts** [comment]
Hi,

Git doesn't support Changelists nor Shelves like Perforce of Plastic SCM so this error in the log is normal.
In Unreal Engine 5.1 the "View Changeslists" entry menu will be greyed out for source control providers not supporting it, so it won't even be an issue.

Cheers!
