### ISSUE TITLE
Plugin was built with a different engine version

### ISSUE THREAD

**Issue by martenzander** [SRombauts/UEGitPlugin#183]
Hey,
probably this is a stupid question, but I wanted to install the git plugin for a UE5 Blueprint project. I copied and pasted the files into the PROJECT/Plugins folder. 

When I try to launch the project, a modal appears telling me that the Plugin "UEGitPlugin" was built with a different engine version. How do I fix that?

Thanks in advance!

**Comment by SRombauts** [comment]
Hello @martenzander 

You would have to compile yourself the plugin, but I have released a ZIP file you can download with both the source code and a compiled version with the DLL: https://github.com/SRombauts/UEGitPlugin/releases
There is one for each recent version of Unreal Engine 5.0, 5.1 to 5.2
